### ISSUE TITLE
Feature: Hotkeys for Media Control

### ISSUE THREAD

**Issue by robertofgama** [aidenlx/media-extended#100]
Hello, first thank you for your work, helps me a loot in my life. 

I want to sugets a improovment, to add the possibility of we define a hotkeys/shortcuts for video control (play/pause, rewind 5s, forward 5s etc).

**Comment by Gigibeau** [comment]
I'd highly appreciate that as well!

**Comment by pascowl** [comment]
The `C` is already working fine but there is no shortcut for the **select captions**. It could be a very powerful feature to switch between different [captions/subtitles](https://github.com/aidenlx/media-extended/wiki/Caption-Subtitle-Support). Maybe `C` could do forward cycle and the `Shift`+`C` could backward cycle. I'm using the same custom shortcut on my MPV player, it's very easier to use like that.

Thanks for creating this convenient extension.

**Comment by aidenlx** [comment]
merge with #133
