### ISSUE TITLE
Feature Request: Open Link modal input area receives cursor focus on opening

### ISSUE THREAD

**Issue by tallguyjenks** [aidenlx/media-extended#105]
when running the command `Open media from link` the modal that pops up doesnt give the input area the cursor's focus to just paste something already on the clipboard and then return focus to the active pane.

Desired Change:

1. running the command opens the modal
2. Cursor is placed in the input area of the modal
3. ability to submit modal by pressing <kbd>enter</kbd>
4. return focus to active pane

this behavior was tested in the help vault with no customizations or other plugins active

**Comment by lofti198** [comment]
+
