### ISSUE TITLE
请添加播放器的代理功能

### ISSUE THREAD

**Issue by CrisWe11** [aidenlx/media-extended#106]
本地用的ss或者trojan，看ytb的学习视频，非常需要一个可以配置代理的地方

**Comment by aidenlx** [comment]
YouTube是跟着系统的代理走的啊，我用clash都没额外配置过，你看看直接嵌入iframe能用不

**Comment by CrisWe11** [comment]
搞明白了。谢谢您的回复，已经解决！ @aidenlx
