### ISSUE TITLE
Feature: Support Live Preview

### ISSUE THREAD

**Issue by ohare93** [aidenlx/media-extended#107]
Recently, Live Preview was added into the stable release of Obsidian. In Live Preview mode a YouTube video does not embed correctly, instead only a blank screen shows :cry: Unsure whether you can do something about it, other than ask the Obsidian devs to help out. 

But just wanted to flag it :+1:

**Comment by DaveyUS** [comment]
Beat me to it 😅

Timestamps support on embeds in Live Preview would be legendary!

**Comment by EhuddR** [comment]
Please we need this feature.

**Comment by DaveyUS** [comment]
> Please we need this feature.

I talked to Aiden on discord about this.. he's currently busy with final exams but it sounds like he'll have some time after. Support him on patreon if you really want to see this feature [https://patreon.com/aidenlx](https://patreon.com/aidenlx)

**Comment by RyzenFromFire** [comment]
Just found this plugin today, this would be a great feature to use!

**Comment by cAtOnana** [comment]
遇到相同的问题，Ctrl+左键点击后没有在embedded window里播放，而是在浏览器上新开了个窗口

**Comment by denemier** [comment]
In the new live preview mode things that I saw not working:
- if I open a video link with timestamp the video doesn't start from timestamp like the normal preview mode instead from the beginning time 0:00
- and also embedded videos with timestamps starts from the time 0:00
- youtube videos doesn't play with native player like in the settings "use built-in controls"
- placeholder in favor of full player option does also not work

**Comment by trey2000** [comment]
"Timestamps support on embeds in Live Preview would be legendary!"

second that!
That would be awesome

**Comment by Elaws** [comment]
This is a great idea !

**Comment by Elaws** [comment]
Also, the audio player can not be resized in live preview, while it is properly resized in reading mode.

Here is the input : `![[Workbench.mp3|350]]`

Below is result in Live Preview :

![image](https://user-images.githubusercontent.com/52013479/154325390-86d13739-8e7d-4711-9fab-a0a2a18e5387.png)

Below is result in Reading mode :

![image](https://user-images.githubusercontent.com/52013479/154325468-76bf0067-65c6-45bb-90ff-a2ad983f7042.png)

Thanks !

**Comment by insanitywanted** [comment]
Media embed with live preview would be a great feature, instead of opening the video in separate tab if it plays inside the editor.
If youtube media playback control (shortcuts) works inside the editor globally it would be game changer. Example: control + space to play/pause the video.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release which provide support for live preview. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
