### ISSUE TITLE
Move the cursor to the end of Timestamp after creation

### ISSUE THREAD

**Issue by Archie-2021** [aidenlx/media-extended#111]
Right now the cursor stay at its position and the timestamp put in front of it, which is inconvenient because the note is supposed to be added in front of timestamp. I am not sure it is because of the new editor or what just thought it can be helpful to be reported.

thanks

**Comment by Elaws** [comment]
This is a great suggestion, I came to suggest this. 

Are there any news on this issue please ?

Thank you !

**Comment by Archie-2021** [comment]
> This is a great suggestion, I came to suggest this.
> 
> Are there any news on this issue please ?
> 
> Thank you !

My guess is tha devs are not active, it has been a while since the last update, hopefully they get active on this project again soon

**Comment by Elaws** [comment]
This is a great plugin for Obsidian, I really hope it will soon keep being improved ;)

**Comment by Archie-2021** [comment]
> This is a great plugin for Obsidian, I really hope it will soon keep being improved ;)

yeah, I am heavily using it and depending on it. just some minor modifications like these and some additional hot keys and it is going to be perfect.

**Comment by leeyupeng** [comment]
I found a temporary solution for this issue.

Download the fixed [main.js](https://github.com/aidenlx/media-extended/files/8145741/main.js.zip) , OR follow the steps below if you prefer to compiling the plugin by yourself.
```
1. Clone the repo.
2. Comment out https://github.com/aidenlx/media-extended/blob/main/src/misc.ts#L48
3. Compile the plugin by running following command. The compiled files will be in 'build' folder.
  npm install
  npm run build
```

Copy the `main.js` file to overwrite`your_valut/.obsidian/plugins/media-extended/main.js`. (You could open the plugin folder in Obsidian's `Settings->Community plugins->Installed plugins` , then click the folder icon `Open plugins folder`)

Another workaround would be enabling `Use legacy editor`. However, this option is not compatible to several popular plugins.

Hope it helps.

**Comment by pmarkaide** [comment]
Not completely sure if I understand your need with the cursor, but I use templater plugin to automatically set where I want to set the cursor. I use the combination of hotkeys CTRL+T to create the timestamp and CTRL+R to "activate" the template, and the cursor is ready to write on the right of the timestamp. Like this:

`[03:56](LINK/TO/YOUTUBE/WITH/TIMESTAMP) YOUR/CURSOR/IS/HERE`

You can define where you want the cursor to be or other things if you define it in the template. For my usage, copy this in the Timestamp template section of the media extended options

`{{TIMESTAMP}} <% tp.file.cursor(0) %>`

All credit goes to Bryan Jenks @tallguyjenks

[Obsidian Media Extended: The Best Way To Take Notes On Videos](https://www.youtube.com/watch?v=GQXVWtNkeZw&ab_channel=BryanJenks
)

**Comment by tallguyjenks** [comment]
i am now using the commander plugin to automate this in a better fashion

using commander to run a macro of inserting the media extended timestamp then running the templater jump to cursor command immediately after 

hotkey for inserting media extended timestamp template now assigned to commander macro and it work beautifully

**Comment by DeiseDaithi** [comment]
Was there any update yet? My cursor goes up and above the timestamp. It would be great if it went right after instead.
