### ISSUE TITLE
Cannot control speed of the video, also not having any other control except pause play when the embedded video file is outside vault but inside local hard drive of computer. 

### ISSUE THREAD

**Issue by debanjanbe** [aidenlx/media-extended#113]
Hi friend, can you please resolve the problem of not having any other control except pause play when the video file is outside vault but inside local hard drive. I am using this code : `<video src='file://G:/New%20folder/my%20new%20video.mp4' width='100%' height='450' controls></video>` to embed a video file which is outside vault.

**Comment by aidenlx** [comment]
raw html code is not supported by media extended, please use `![](file://G:/New%20folder/my%20new%20video.mp4)`

**Comment by debanjanbe** [comment]
not solved. The link you have written is not linking the video file outside obsidian vault. Nothing is showing.

**Comment by aidenlx** [comment]
maybe try `![](file:///G:/New%20folder/my%20new%20video.mp4)`?
