### ISSUE TITLE
支持的视频编码格式有哪些

### ISSUE THREAD

**Issue by UltramarineSky** [aidenlx/media-extended#114]
从B站上下载视频，视频编码格式为H.265/HEVC，用file协议以本地文件格式插入obsidian里，播放为黑屏，不显示画面；将编码换成H.264/AVC的，正常播放。

请问media extended支持的视频格式有那些

**Comment by aidenlx** [comment]
取决于Obsidian（桌面版对应Electron的Chromium引擎/手机上的WebView）的版本，目前来看HEVC除了iOS之外基本都不支持（在桌面版录音得到的的ogg编码的文件在iOS也打不开😂），Media Extended没有对Obsidian本身支持的编解码做拓展

**Comment by UltramarineSky** [comment]
> 取决于Obsidian（桌面版对应Electron的Chromium引擎/手机上的WebView）的版本，目前来看HEVC除了iOS之外基本都不支持（在桌面版录音得到的的ogg编码的文件在iOS也打不开😂），Media Extended没有对Obsidian本身支持的编解码做拓展

好的，谢谢解答
