### ISSUE TITLE
Bug: Player Maximize issue 

### ISSUE THREAD

**Issue by faysalforbd** [aidenlx/media-extended#120]
https://user-images.githubusercontent.com/22533345/154231888-920d65c4-943c-47ad-a97b-45f43b224447.mp4

**Comment by aidenlx** [comment]
have you tried to disable custom theme and css snippets? it might be css issue.

**Comment by faysalforbd** [comment]
I tried again after your response with a brand new valut. I'm not knowledgeable of any such problem. Thank you for your response, and also for this fantastic plugin.
