### ISSUE TITLE
Resizing the audio player leads to display bugs below a certain point.

### ISSUE THREAD

**Issue by Elaws** [aidenlx/media-extended#121]
Hello,

I wanted to resize audio player so that it fits in a dataview table. Unfortunately, below 200px (which is still quite large for a dataview table), the audio player does not display properly :

![image](https://user-images.githubusercontent.com/52013479/154324985-f423e444-302c-4716-a1f3-85b6d5f0a888.png)

(Input is : `![[Workbench.mp3|200]]`)

Is there any way to solve this problem ? 

Thanks

**Comment by aidenlx** [comment]
you can hide some controls in the settings to make it works better, but I think 200px for audio player is a bit too small (at least smaller than the min-width of plyr)

**Comment by Elaws** [comment]
Thanks, nice workaround. It would be nice that resize would be responsive, so it could fit several usecases. 

> at least smaller than the min-width of plyr

I changed `Minimum Player Width for Embeds` but it had no effect.

**Comment by aidenlx** [comment]
`Minimum Player Width for Embeds` can't change the width of each button, only the overall size so it can't solve your problem. as for dynamic controls, I'm waiting for [next version of plyr](https://github.com/sampotts/plyr/issues/2408) to provide better control over components. for plyr in current version of media extended, it's something difficult to achieve.

**Comment by Elaws** [comment]
@aidenlx : Thanks, this is great news !
