### ISSUE TITLE
Can not open video with embedded player by click link

### ISSUE THREAD

**Issue by tutututu7521** [aidenlx/media-extended#123]
Hi, this plugin is quite helpful!

However, I can not just click on the link to open the embedded player and play the video, as shown in your demo. Only "link to the media" command is work. 

All Settings have been checked and there are no problems. 

How can I make it so that I can open the embedded player with click?

**Comment by tutututu7521** [comment]
I just noticed that clicking on a link is ok in reading mode, but can't add a timestamp, and if in edit mode, I can only open the embedded player by "Enter Link to Media". So, is it possible to click the link to open the embedded player in edit mode?

**Comment by XMB-7** [comment]
There is a workaround. Use the hotkey ctrl+e switching to the reading mode first, open an embedded video view, then go back to the edit mode with ctrl+e again to add timestamps.

**Comment by aidenlx** [comment]
merge with #107, should be fixed once that issue is closed
