### ISSUE TITLE
Clicking on links show black screen

### ISSUE THREAD

**Issue by Archie-2021** [aidenlx/media-extended#125]
After updating to Obsidian.0.13.30 it shows a black screen (don't open) youtube.

![image](https://user-images.githubusercontent.com/85870778/158012051-f7d89ed4-ab5a-4b97-8e21-eeea30173d47.png)

I heavily use this great plugin, please help

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
