### ISSUE TITLE
开发者你好，有考虑增加截图按钮功能吗？

### ISSUE THREAD

**Issue by yukminnie** [aidenlx/media-extended#126]
感谢您开发这么好用的插件功能。

我有个不成熟的想法，如果是使用外置截图软件，实际上是可行的，不过总归清晰度方面，没有截取关键帧画面来的好，有没有计划增加这一功能呢?

**Comment by aidenlx** [comment]
已经实现了，目前在测试新的底层播放器，推送正式版还要一段时间

**Comment by yukminnie** [comment]
> 已经实现了，目前在测试新的底层播放器，推送正式版还要一段时间（iOS端目前都不可用，需要等苹果更新WebKit正式推送Experimental MediaSource Inline Painting支持）

手动笔芯♥♥♥

**Comment by aidenlx** [comment]
merge with #31
