### ISSUE TITLE
Global media playback control

### ISSUE THREAD

**Issue by insanitywanted** [aidenlx/media-extended#127]
I am using this plugin to take notes from the youtube videos and my current workflow looks like this:
1. Move to media tab (where youtube video is playing)
2. Pause the video and grab the timestamp using the hotkey
3. Write the the note about that timestamp
4. Move back to the media tab and play the video 
5. Repeat again from step 1

This process is cumbersome as we have to jump between the tabs oftentimes. It would be much easier if we control the media/video playback from the tab where we are writing the note.

**Possible solution:** Ability to add the hotkey/shortcut to control the media playback from anywhere inside the obsidian

If anyone has a better workflow please let me know

**Comment by aidenlx** [comment]
merge with #133
