### ISSUE TITLE
Issue with the video player appearance

### ISSUE THREAD

**Issue by stackingflow** [aidenlx/media-extended#128]
Media player takes the whole height of the screen

![Screenshot 2022-03-20 at 7 47 06 PM](https://user-images.githubusercontent.com/47140829/159166904-36645ffe-4379-4938-a5f1-ecd17571c7df.png)

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
