### ISSUE TITLE
Feature Request: play video from the corresponding time by clicking the timestamp in editor

### ISSUE THREAD

**Issue by lofti198** [aidenlx/media-extended#132]
Desired scenario
1. user click on previously saved timestamp in editor
2. player starts playing from the corresponding time

![image](https://user-images.githubusercontent.com/42960488/163711316-910af5d9-6b21-4acc-8d1c-8f255e438724.png)

**Comment by lofti198** [comment]
UPDATED! It works completely fine in Preview mode, however missing in LivePreview

**Comment by aidenlx** [comment]
duplicate of #107

**Comment by lofti198** [comment]
Sorry for my lack of knowledge - can I take this pull request draft and somehow compile on my local machine?
