### ISSUE TITLE
The problem of interface display 

### ISSUE THREAD

**Issue by wutaotao0711** [aidenlx/media-extended#135]
I'm new to Obsidian, I setup the plugin, then the display is abnormal, and many interfaces appear, like this.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/104780985/166262019-cea7894d-ca6b-4555-96d6-9b0df16175c0.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/104780985/166262067-92321390-18d8-43b8-80ec-01cae5a47419.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/104780985/166262079-028f3c91-87d5-4c3c-8211-8c5dfcecd53d.png">

hope your reply  :）

**Comment by aidenlx** [comment]
你是手动装的吧，检查一下插件文件夹里有没styles.css

**Comment by wutaotao0711** [comment]
是缺少了styles.css，从新下载了插件，已经解决问题。谢谢~~~

**Comment by wutaotao0711** [comment]
延伸的问题：B站的视频嵌入OB后，画面模糊。不知道什么原因。
视频路径：https://www.bilibili.com/video/BV1Dy4y1375P

<img width="416" alt="image" src="https://user-images.githubusercontent.com/104780985/166391017-8fff4e4c-7554-4bc5-aed4-71b3b8dafde2.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/104780985/166391023-86403bea-298f-4252-a13f-209b05666fe2.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/104780985/166391033-e039dd31-3bb6-4561-a434-a9cf9e2567b1.png">

**Comment by aidenlx** [comment]
这个目前没什么好办法，根本解决要等v3，你可以试试打开其他的视频再开bilibili的试试

**Comment by wutaotao0711** [comment]
好的，坐等新版本😄
