### ISSUE TITLE
Audio will not play on linked page

### ISSUE THREAD

**Issue by chrismelbourne** [aidenlx/media-extended#137]
**To reproduce the bug:**
1. Create a new page (e.g. "Audio.md") and insert an .mp4 file.
2. Create a second page, and create a link:
`[[Audio]]`
3. Switch to Reading Mode
4. Hover over the link. A popup will appear showing the audio play button.
5. Click the Audio play button.

**What happens:**
Nothing plays.

**What should happen:**
Audio should play.

Control test:
1. Turn off media-extended plugin
2. Repeat above steps 
3. The audio will play normally.

**Comment by thiavila-sigma** [comment]
same here

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
