### ISSUE TITLE
Support for non-YouTube videos

### ISSUE THREAD

**Issue by DutchPete** [aidenlx/media-extended#139]
Hi, I just picked up your extension from [Bryan Jenks](https://discord.com/channels/686053708261228577/710585052769157141/978317597005185075). I make notes from videos regularly, so this extension will be of great help.

However, I also use videos from non-YouTube sources, such as e.g. Rumble, BitChute, Odysee, etc. The extension does not seem to support non-YouTube channels. Is there a possibility to offer support for these too?

**Comment by aidenlx** [comment]
yes, it's already a part of the plan of v3 to support any website with webview player.

**Comment by DutchPete** [comment]
OK, sounds good, many thanks.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
