### ISSUE TITLE
Feature: Speed Options Lacking

### ISSUE THREAD

**Issue by austingergen** [aidenlx/media-extended#140]
Not sure if this is possible, but adding custom playback speeds to the settings tab would be a great feature add, as well as keyboard shortcuts to adjust the speed on a 10% increment similar to the video speed controller chrome extension

**Comment by Vuccappella** [comment]
Already have a request for this here: https://github.com/aidenlx/media-extended/issues/77

**Comment by lisah2u** [comment]
Plug for this, as well. I use embedded media for backing tracks -- so more fine-grained options below 100% would be great. 10% increments seem fine, though any way to customize speed even in a settings file would be great.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release, which addresses this issue. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
