### ISSUE TITLE
obsidian 0.15.6  bug

### ISSUE THREAD

**Issue by wen00** [aidenlx/media-extended#145]
1. 点击时间戳后，切换编辑和预览的功能，视频窗口下方出现预览文本的窗口。如果来回切换预览和编辑，文本会变得更多的现象。
2. 另外希望插件可以支持bilibili，多数场景下都在用ipsd

**Comment by bibibimartyr** [comment]
![IMG_0380](https://user-images.githubusercontent.com/49381756/179336906-7c3b6824-1477-492e-8fcd-9c4329be718b.jpeg)

我也有这样的情况，现在没办法用了，如果打开PDF就没有这样的现象发生。

**Comment by bibibimartyr** [comment]
https://user-images.githubusercontent.com/49381756/179336939-96a912d2-0dd2-4a71-a55f-5aa613e58c4c.mov
我也有这样的情况，如果打开PDF就不会有这样的情况发生，因此我觉得应该是这个插件的问题，大佬还会更新吗，希望大佬修复，现在完全没有办法使用了。

**Comment by qiaogaojian** [comment]
same issue to me

**Comment by demonhumen** [comment]
![image](https://user-images.githubusercontent.com/12506447/179379857-6e56268c-b853-4384-8055-9b83cd86f0b6.png)

**Comment by ibingshanmine** [comment]
同样遇到了这样的问题

**Comment by yuhixyz** [comment]
+1

**Comment by jsjuris89** [comment]
+1, same issue also.

**Comment by ibingshanmine** [comment]
求大佬更新一下

**Comment by huairenlian** [comment]
+1，早知道就关闭obsidian的自动升级了

**Comment by huairenlian** [comment]
兄弟们，还是把obsidian降级到0.14.xx版本的吧，具体---->（先用geek卸载obsidian，可以连其注册表一并删除，否则无法降级，然后用之前的0.14.xx的安装包重新安装，安装时候要断网，否则会自动升级最新版本）先用低版本的吧，静候作者大大更新吧

**Comment by leedh** [comment]
+1 same here

**Comment by DustlyFog** [comment]
+1 same here

**Comment by whyihaveyou** [comment]
可以先点右上角的断开链接，切换之后再重新链接，麻烦一点

**Comment by JeffChien** [comment]
就先用三個 panels 吧，先把文件切割成兩個 panels，把一個轉成 preview mode，用 preview mode 開影片，這樣三個 panels 都會正常工作。 有點小麻煩但是還可用。

**Comment by paczkow** [comment]
+1 same here. Any updates?

**Comment by starsea** [comment]
我真是要疯了 作者不更新了吗？

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
