### ISSUE TITLE
windows wont open the timestamp link to a file 

### ISSUE THREAD

**Issue by Mahgozar** [aidenlx/media-extended#146]
every time i want to open a link with time stamp to my file it shows me the following error 
![image](https://user-images.githubusercontent.com/54596777/178710108-729635ec-97da-42e8-ac64-8c9272d34718.png)
and its the same for all files

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
