### ISSUE TITLE
编辑模式下打开超链接会跳转到浏览器而非内部查看

### ISSUE THREAD

**Issue by TheTusss** [aidenlx/media-extended#147]
几天前都还行，不知道是因为版本更新还是哪里设置错了？
版本：v0.15.6

**Comment by dyxdyxdyx** [comment]
预览模式下会在内部跳转视频

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
