### ISSUE TITLE
Truncate time to seconds

### ISSUE THREAD

**Issue by Smitty010** [aidenlx/media-extended#148]
It would be nice if the time could be truncated to the nearest second.  The URLs are long enough as it is.  I realize this is an enhancement.  Maybe it should be an option

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
