### ISSUE TITLE
似乎 时间戳链接无法分享给别的文件使用

### ISSUE THREAD

**Issue by homuraLan** [aidenlx/media-extended#149]
我在将时间戳分享给别的文件时，只能够加载视频不能正确得读取时间戳

**Comment by Sincejunly** [comment]
已解决和https://github.com/aidenlx/media-extended/issues/147是同类型替身

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
