### ISSUE TITLE
Feature: Enable Bilibili timestamp control

### ISSUE THREAD

**Issue by aidenlx** [aidenlx/media-extended#15]

**Comment by okerivy** [comment]
[bilibili] can add `t=10s`
https://www.bilibili.com/video/BV1Ut411u7H4?p=2&t=10s 
OR add `t=0h2m10s`
https://www.bilibili.com/video/BV1Ut411u7H4?p=3&t=0h2m10s
Thank you

**Comment by okerivy** [comment]
Hopefully YouTube will add other jump formats `?t=` because there are other styles for the default copy back format.
Such as this `?t=299 ` 
This is currently the only support`#t=299 `

 https://youtu.be/FuKEpOhiVPg?t=299  can't jump
 https://youtu.be/FuKEpOhiVPg?#=299  can jump
