### ISSUE TITLE
[BUG] When changing from Live-preview mode to reading mode a new pane gets opened in loop

### ISSUE THREAD

**Issue by ironhak** [aidenlx/media-extended#151]
1. Create a new note
2. Insert a video URL
<img width="953" alt="Screen Shot 2022-08-15 at 22 47 38" src="https://user-images.githubusercontent.com/62611612/184715621-f1a7c123-ac3d-4bd9-b2d2-e3aa652ba05d.png">
3. Switch to edit/live-preview mode
4. ctrl/cmd+p -> Open media from link
5. Paste the same link
6. Start the video, take some notes
<img width="1788" alt="Screen Shot 2022-08-15 at 22 49 02" src="https://user-images.githubusercontent.com/62611612/184715815-fa258a2e-df5c-43ca-8751-0acdb277388e.png">
7. Switch from Edit/Live-preview to reading
<img width="1794" alt="Screen Shot 2022-08-15 at 22 49 16" src="https://user-images.githubusercontent.com/62611612/184715859-eb2b1b6a-7b5e-4998-8654-059e1e731592.png">
Here's what's happen
8. Switch another time from edit to reading mode
<img width="1800" alt="Screen Shot 2022-08-15 at 22 49 44" src="https://user-images.githubusercontent.com/62611612/184715949-72b8b114-482c-48f5-8e63-bf68ab754cec.png">

This goes on endlessy... Hope someone can resolve. Thank's.

**Comment by yuhixyz** [comment]
## Current Solution
Before you switch mode, first `Unlink pane`, after you switch mode, choose `More options > Link with pane...`.

## Another Solution 
Downgrade you obsidian to v0.14.15. Remember to disconnect the wifi before you open obsidian v0.14.15, then turn off `About > Automatic updates`.

**Comment by ironhak** [comment]
Hi, thank’s. Is the author going to fix this any time soon?

Than’s for giving a solution.

**Comment by JeffChien** [comment]
I came up a workaround to this issue instead of switching mode back and forth, just use 3 panels.
first split the editor into 2, then turn one into preview mode, click timestamp link in preview panel will open a video panel and all 3 are linked.

**Comment by JumpStatus** [comment]
> ## Current Solution
> Before you switch mode, first `Unlink pane`, after you switch mode, choose `More options > Link with pane...`.
> 
> ## Another Solution
> Downgrade you obsidian to v0.14.15. Remember to disconnect the wifi before you first time open obsidian v0.14.15, then turn off `About > Automatic updates`.

# sorry,why it's still not working with v0.14.15?

**Comment by ironhak** [comment]
Hi, thank’s. Is the author going to fix this any time soon?

Than’s for giving a solution.

**Comment by Eleenventtt** [comment]
> ## Current Solution
> Before you switch mode, first `Unlink pane`, after you switch mode, choose `More options > Link with pane...`.
> 
> ## Another Solution
> Downgrade you obsidian to v0.14.15. Remember to disconnect the wifi before you first time open obsidian v0.14.15, then turn off `About > Automatic updates`.

That works. Thank u!

**Comment by fireflysss** [comment]
this bug is when edit/live-preview mode ,it make anther. i use callouts, put timestamps into >[!note].And  setting like this
![image](https://user-images.githubusercontent.com/128112676/225801488-927c8101-11e9-4893-93e4-e7ddf66a1f21.png)

**Comment by blumenschwein** [comment]
> this bug is when edit/live-preview mode ,it make anther. i use callouts, put timestamps into >[!note].And setting like this

It does not work.

**Comment by fireflysss** [comment]
> > this bug is when edit/live-preview mode ,it make anther. i use callouts, put timestamps into >[!note].And setting like this
> 
> It does not work.
you can see this
https://forum.obsidian.md/t/fix-problem-with-media-extended-plugin-when-switch-from-editing-to-reading/56432

**Comment by marsvet** [comment]
> this bug is when edit/live-preview mode ,it make anther. i use callouts, put timestamps into >[!note].And setting like this ![image](https://user-images.githubusercontent.com/128112676/225801488-927c8101-11e9-4893-93e4-e7ddf66a1f21.png)

@fireflysss It works! Thanks a lot!

**Comment by 2-3-5-7** [comment]
> I came up a workaround to this issue instead of switching mode back and forth, just use 3 panels. first split the editor into 2, then turn one into preview mode, click timestamp link in preview panel will open a video panel and all 3 are linked.

I recommend using JeffChien's method because it can be embedded in a list, although fireflysss's callouts method also works, it is not as flexible as a list when adjusting levels.

Here is image of the two methods

![image](https://github.com/aidenlx/media-extended/assets/79762374/b0d8258a-ed6c-401b-be5b-05b30f5f2ae5)

**Comment by bfcs** [comment]
it's about the  function, setGroupMember()

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
