### ISSUE TITLE
[bug?]Unable to adjust video progress

### ISSUE THREAD

**Issue by homuraLan** [aidenlx/media-extended#152]
After clicking the jump timestamp, the video progress cannot be manually adjusted, otherwise it will automatically return to the timestamp

**Comment by JeffChien** [comment]
how about change the setting to use the youtube builtin controller instead?

**Comment by Zumh** [comment]
> how about change the setting to use the youtube builtin controller instead?

I got the timestamp but can't jump. It just open my system browser instead and start from the beginning. 
both doesn't work

**Comment by JeffChien** [comment]
check my workaround in this tread
https://github.com/aidenlx/media-extended/issues/151

also make sure all 3 panes are linked, check if you see the red chain icons on the top right corner of all panes, if not there's a `link with pane` button  inside the more tools dropdown menu.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
