### ISSUE TITLE
Plz support cursor set loop timestamp for learning language.

### ISSUE THREAD

**Issue by Connor-yang96** [aidenlx/media-extended#154]
Plz support cursor set **loop timestamp** for learning language and some skills(Photoshop , Blender3D skills) .

The template better is this: 
`![hello world](file:///D:/test.mp4#00:03:31,00:05:00&loop)`

Thank you !

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
