### ISSUE TITLE
Watching private youtube videos

### ISSUE THREAD

**Issue by Hameds** [aidenlx/media-extended#155]
Hi,

Thanks for this wonderful plugin. I was wondering if you can add support to watch private youtube videos? It seems that the Youtube Player has an option for `Account`. I am not sure if there is any way to add token or login using username and password to authorize watching my private youtube videos.

![media-extended-private-video](https://user-images.githubusercontent.com/1385656/185783345-aa303a76-e12b-4ff6-a372-dd35a141f47a.png)

**Comment by Keysz** [comment]
Agreed - I would like to know if there is a way to watch private videos as well

**Comment by hanw** [comment]
Please enable this.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release, which supports open YouTube website inside obsidian. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
