### ISSUE TITLE
请问现在支持了live preview了吗？

### ISSUE THREAD

**Issue by learnpythontheew** [aidenlx/media-extended#157]
live preview 用 <iframe> 嵌入网络视频总是自动播放。
想停掉自动播放，找到了这个插件。
请问现在支持live preview了吗？

**Comment by scruel** [comment]
不支持，用 live preview 直接全乱了，点击也是会直接打开网页

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
