### ISSUE TITLE
Option to open video to the left.

### ISSUE THREAD

**Issue by jostid** [aidenlx/media-extended#158]
I prefer to have the notes pane to the right of the video pane.

Would be very nice to have the video to open up "to the left". Could be a switch in the settings?

Thanks for a great plugin!

/Jonas

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
