### ISSUE TITLE
The timestamped link always start at the beginning of youtube video: how I solve it

### ISSUE THREAD

**Issue by pmarkaide** [aidenlx/media-extended#160]
This plugin is very nice, but seems to be death now. For anyone having this problem and access to a terminal, I use this commands to fix all links on the note **after** I have finnished taking notes on it.

```
sed -i s#https://www.youtube.com/watch?v=#https://youtu.be/#g YOUR_NOTE.md
sed -i s/#t=/?t=/g YOUR_NOTE.md
sed -i 's/.[0-9]*)/)/g' YOUR_NOTE.md
```

**Test it first and be sure you don't have other matching lines before applying it!**

This is an awful solution, but it fix the problem for me.

**Comment by mkrump** [comment]
Same issue. The links for youtube videos are not integers (eg `link#t=80.97703`) and [youtube API only supports integers](https://developers.google.com/youtube/player_parameters?hl=en#start) so every link just starts at the beginning of the video for me. Is there anyway to change the format of the timestamp to an integer?

**Comment by mkrump** [comment]
Also, same problem @pmarkaide pointed out with the `#t=` needing to be replaced with `?t=`

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
