### ISSUE TITLE
Embedded video is not recognized by the media-extended.

### ISSUE THREAD

**Issue by Ao-Last** [aidenlx/media-extended#161]
## Steps to reproduce:
1. Add an video embed using the following statement. 
```
![Lec 6](https://youtu.be/fRGo50Wuql0?list=PLoCMsyE1cvdVnCgHk43vRy7PVTVWJ6WVR)
```
2. Switch to view mode, and playing the video.
3. Open command panel, no taking timestamp option.
![image](https://user-images.githubusercontent.com/63785048/190907179-af3a06d2-00a7-4f67-879b-b5a3d41d6a01.png)
---
While it is true that the option "Open Media From Link" works well,

**Comment by mrkuramoto** [comment]
Same problem after the Obsidian v0.16

**Comment by Gr-Nobel** [comment]
Same

**Comment by Flavinsh** [comment]
Same issue here (Obsidian 1.3.5 on macOS 12.6.6).

Would love to be able to insert timestamps while watching the video _directly embedded_ in the note (i.e. _not_ in the side bar).

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
