### ISSUE TITLE
Audio waveform

### ISSUE THREAD

**Issue by 23tux** [aidenlx/media-extended#162]
Is it possible to somehow display the waveform of an audio recording? I have a lot of recordings and it would be immensely helpful when the waveform would be displayed above/below/inside the scrub bar.

Any chance that this is a feature you would consider? I saw this issue from last year https://github.com/aidenlx/media-extended/issues/86 asking a similar thing for videos.

**Comment by aidenlx** [comment]
Will be traced in #86
