### ISSUE TITLE
bug 时间戳使用ctrl+鼠标左键点击，无法在内部打开视频

### ISSUE THREAD

**Issue by zhouchiyan82** [aidenlx/media-extended#163]
打上时间戳后，不能在实时预览模式中，用ctrl+左键 打开视频。会直接弹出网页。只能在阅读模式下才生效

obsidian版本 v0.15.9

**Comment by Another5405** [comment]
I have the same problem with this , let me translate to english.
```
timestamp is not working if using live preview mode, it will pop out website with your default browser.

obsidian version v0.15.9
```
and my version is v1.1.9 which is still not working

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
