### ISSUE TITLE
能否在画中画模式下可以全屏功能？

### ISSUE THREAD

**Issue by zhouchiyan82** [aidenlx/media-extended#164]
如果画中画打开，我就可以在第二个显示器内观看视频，在第一个视频中记录笔记。希望能加入！！！！感谢
If picture-in-picture is on, I can watch videos on the second monitor and take notes on the first. Hope to join

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
