### ISSUE TITLE
Subtitle files seems not supported after Obsidian 1.0

### ISSUE THREAD

**Issue by pascowl** [aidenlx/media-extended#165]
My media and subtitle files are in the same folder, but after Obsidian's 1.0 update it seems the extension need to update.

I just wanted to let you know. Thanks! 🙏

**Comment by friendtasy** [comment]
it will work in preview mode.....

**Comment by 2-3-5-7** [comment]
@friendtasy no, it didn't work

**Comment by friendtasy** [comment]
> @friendtasy no, it didn't work



https://github.com/aidenlx/media-extended/assets/17196859/325cbac1-4511-4c5c-b9aa-25ce1d7a7687

**Comment by 2-3-5-7** [comment]
@friendtasy This is not helpful at all, I can also post a video to show there are no subtitles.

**Comment by friendtasy** [comment]
> I found the reason, the subtitle function does not support network files, and local files must be in the vault

maybe the network files can't be load?

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.

**Comment by friendtasy** [comment]
> 对于该项目长期不活跃表示歉意。我想通知您，该插件已针对 v3 版本进行了完全重写。我目前正在准备测试版。一旦可用，如果您遇到类似问题，请随时打开新问题。感谢您的理解。

great!!!
