### ISSUE TITLE
Will local video be supported in the future?

### ISSUE THREAD

**Issue by FinderBGG** [aidenlx/media-extended#169]
Will local video be supported in the future?

**Comment by merlinuwe** [comment]
Have you tried this?

![](../../attachments/Small.mp4#t=3,5)

**Comment by FlorianLiebhart** [comment]
It also works to do this:
`[[MyVideo.mp4#t=8]] `
However, one point that is not supported is opening local files, is opening the local file with the command palette `Open Medie from Link`  (unless you use file:/// but then it is absolute, which we don't want).

**Comment by bkushigian** [comment]
Hey all, I'm also having a hard time working with local videos. I am on Windows (not my choice!) and I am looking for the "insert timestamp" functionality. It works for Youtube videos that I've opened from link, but I can't find a way to open local files from link (maybe there's a magical `file:///` incantation that works with Windows file paths but I've tried everything I can think of).

Also, using `![](../../attachments/My-video.mp4)` doesn't work, and the `[[My-video.mp4#t=8]]` syntax opens the video but not to the timestamp.

**Comment by FlorianLiebhart** [comment]
Hello Been!

Relative paths are not possible, this is why the first one doesn't work.

Regarding the second one: Have you tried it on read mode? In edit mode it
doesn't work .

Regarding Windows: lol 😂
I found it funny how you are saying it is not your choice :D

Ben A Kushigian ***@***.***> schrieb am Mi., 30. Nov. 2022,
20:28:

**Comment by kerim** [comment]
Oh, too bad. I was hoping I could use this with local media files....

**Comment by heliocarbex** [comment]
You can. But today it only supports mp4. But if you change the file main.js, you can add more formats. I added mkv: 
change ["video", ["mp4", "ogv"]] to ["video", ["mp4", "ogv","mkv"]]

**Comment by heliocarbex** [comment]
Put [[your funny video.mp4#t=1]] on a obsidian note and change to reading view and click the link.

**Comment by heliocarbex** [comment]
If you do what I said above to mkv, you can do the same to this format.

**Comment by SuperMaxine** [comment]
> You can. But today it only supports mp4. But if you change the file main.js on your local .obsidian (dot obsidian) folder, you can add more formats. I added mkv: change ["video", ["mp4", "ogv"]] to ["video", ["mp4", "ogv","mkv"]]

Huge thanks, this solution definitely solved the problem I was having

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
