### ISSUE TITLE
Bug with linked video pane, and some fit options

### ISSUE THREAD

**Issue by Darkbluetest** [aidenlx/media-extended#170]
Hi

It is a nice and useful plugin, thanks. But I have some suggestions and a bug:

The suggestions, is to remove the black background around the video in case it has not the shape of the pane, and to allow to set the size (minimum, maximum, like for the embedded one) for the local video in the vault when opened directly in a note.

The bug is that when a pane with the video is linked to a note where you put the timestamps, each time you enter in edit mode, in the linked pane with the video appends, below the video, a copy of the linked note. I use Obsidian 1.0.3

You can only remove it by closing the video pane and reopening it.

Thanks

**Comment by Darkbluetest** [comment]
Hi, I see this bug is already reported here: https://github.com/aidenlx/media-extended/issues/159

BTW, improvement idea: to have the video embedded in the note, and several timestamps links that plays the embedded video without need to have another pane open linked to the note's one. It would be very practical and neat. Do not know if it is possible, though.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
