### ISSUE TITLE
Several notes sharing one video pane

### ISSUE THREAD

**Issue by Darkbluetest** [aidenlx/media-extended#172]
Hi

Is it possible to have a pane to show the video of any pane opened that is showing a note? I mean, for example, to have two panes open, both with two different notes but each note has links to some timestamps of some videos. A third pane is where the videos are shown. Each one of the two first panes is linked to the video pane. This works, only that the two panes with notes, are showing always the same note (as they are linked both through the link to the video pane). Is there some way to avoid this behaviour? If not, could this functionality be fixed or added?

Thanks

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
