### ISSUE TITLE
Total duration is displayed as "00:00" instead of its real value

### ISSUE THREAD

**Issue by Elaws** [aidenlx/media-extended#174]
# Description

![image](https://user-images.githubusercontent.com/52013479/205367144-51c36d77-dfe5-4ce6-a556-1119f006425b.png)

YouTube link tested : https://youtube.com/watch?v=wjq9F_EFtOA

# Environment

Windows 11
Obsidian 1.0.3
Media extended 2.11.1

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
