### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by bestdax** [aidenlx/media-extended#175]
希望增加toggle_play，forward, rewind,  repeat的command，这样我就可以通过leader_hotkeys来实现听写的时候不离开笔记进行音频的播放控制。没学过js，而且这个源码也太长了。麻烦了。

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
