### ISSUE TITLE
Player timestamp syntax for YouTube

### ISSUE THREAD

**Issue by ChaplainTIG** [aidenlx/media-extended#176]
For me to get the links to work for YouTube, they need to be with an "?" (insted of an "x") and have to be a non-decimal. Is there a way to modify the timestamp syntax?

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release, which has addressed this issue. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
