### ISSUE TITLE
Player control buttons blank in light mode of Obsidian

### ISSUE THREAD

**Issue by Darkbluetest** [aidenlx/media-extended#178]
Hi

The title summarizes, it. In dark mode it is ok, but in light mode, the buttons of the player are all white/blank. I am using 2.11.1 in last Obsidian version 1.1.9. Here you can see an screenshot:

![Snag_e729f3a](https://user-images.githubusercontent.com/48590261/215266599-5c4acc1d-b4c5-4389-95d0-50a3eab9adf2.png)

I have tried and disabled all plugins, restarted Obsidian, but no change. It is always like that. Could it be fixed, please?

Tx

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
