### ISSUE TITLE
Function: Solve the pain point of taking notes while watching online lessons. Can I use a shortcut key to control the video playback in the preview interface in the editing interface

### ISSUE THREAD

**Issue by elilau755** [aidenlx/media-extended#179]
For example, I hope that the premise is to be able to meet the editor and take notes at the same time. Can control the pause of the preview interface video through the global shortcut key, and fast forward and backward shortcut key function, thank you!

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
