### ISSUE TITLE
Player too big vertically on certain Android phones

### ISSUE THREAD

**Issue by agsoto** [aidenlx/media-extended#182]
Hi, when I open any video from Youtube, the proportions are automatically defined and work pretty good on desktop but it could fail on mobile: the controls are partially hidden. This happens with Youtube's native controls also. I've tried setting the maximum height to 0.8vh and 500px but it seems to have no effect on the resulting size:
<img alt="Screenshot_20230421-081041_Obsidian" src="https://user-images.githubusercontent.com/70116396/233645435-73de0736-b7c0-4e0e-bc4b-d0c4bef87c43.png" width="300">
The phone screen tested has a 1080 x 2340 px, and 19.5:9 ratio. Is there a known fix for this?

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
