### ISSUE TITLE
local file support

### ISSUE THREAD

**Issue by username-8** [aidenlx/media-extended#184]
i remember linking to huge (hour & half 2 hours long) lectures and taking time-stamped notes on them a few months back. 
i don't know how i did it but i remember doing it. 

is that feature gone or am i doing something wrong??

i'm trying to add links like 

- `file:///D:/%F0%9F%92%8EOBSIDIAN%F0%9F%92%8E/%E2%99%A5%20UPSC%20%E2%99%A5/ZzZ/z-av/Every%20Year%20of%20Indian%20Colonialism.mp4`
- `D:\💎OBSIDIAN💎\♥ UPSC ♥\ZzZ\z-av\Every Year of Indian Colonialism.mp4`
- & even
`obsidian://open?vault=%E2%99%A5%20UPSC%20%E2%99%A5&file=ZzZ%2Fz-av%2FEvery%20Year%20of%20Indian%20Colonialism.mp4`

mind you this sample video is tiny 2.5 minutes long and it still is not working

**Comment by rgraus** [comment]
I have the same problem. Just some weeks ago, I could watch local files and add timestamped notes, but now it is not working anymore.

**Comment by username-8** [comment]
so.... any idea on how to fix this ???
i.e. what shout i type in "open medi from link" based on the rules given below? 
could u please give me an example??? 
![image](https://github.com/aidenlx/media-extended/assets/80767842/97570b8a-46d1-428a-8add-4d53c24388b1)
> ![resim](https://user-images.githubusercontent.com/111116092/249911367-b6f7b170-1428-4df9-9ab2-391f64dad609.png)

**Comment by fastrick** [comment]
Is there any way to change it in Obsidian to enable just this Plugin to access using the link: `file:///D:/...`

**Comment by Zachatoo** [comment]
> There is no fix for us users, obsidian plugin authors have to add a new call method to their plugins. Bad change that such useful and common features are now only accessible through internal calls, why not adding an option in preferences instead to break things? :((((

Because it's a security issue, and Obsidian wants to protect their users? The devs have provided a more secure alternative to be able to support the same functionality, someone just needs to make a PR to fix it.

**Comment by vonlaughing** [comment]
If you can, please fix this, this plugin would be a game changer for me if local file support works. Thank you again!!

**Comment by KSK417** [comment]
Hope there have a fix version.
I saw a 中文forum was try to fix the local file media problem.
They also try hard but still can't fix it. 
Hope can update it and will support if there have update.
Thanks.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.

**Comment by username-8** [comment]
still facing the same
