### ISSUE TITLE
External links!!!

### ISSUE THREAD

**Issue by OmarBinSaad** [aidenlx/media-extended#188]
Hello, This is Omar, I hop you are doing well
First of all thank you for you efforts in the plugin. I would like to tell you about little issue that when I use this plug in and take some note, when I click on the time, it open the link in new window each time.

The 'timestamp note' is plugin as same as your plugin that open the links in side "Obsidian" and the video gose excactly to the minutes with out need to open the browser.

so I hope to fix this issue and make the links open inside "Obsidian" with out need to the browserat all.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release which provide a new feature to open any webpage inside obsidian. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
