### ISSUE TITLE
Great tool, but the Youtube timestamp is no longer valid

### ISSUE THREAD

**Issue by JackyWay** [aidenlx/media-extended#190]
The timestamp captured by the tool below is not functioning. 
`https://www.youtube.com/watch?v=T4Df5_cojAs&ab_channel=kubucation#t=488.7268409408722`

However, it works for the subsequent timestamp.
`https://www.youtube.com/watch?v=T4Df5_cojAs&t=488s`

Could you fix this? Thank you so much.

**Comment by nanhualyq** [comment]
`<iframe src="https://www.youtube.com/embed/dqpTOGmghfM?start=20&end=22" />`

This works for me.

**Comment by danbaragan** [comment]
Happens to me too.
For clarification, url timestamps of this form `#t=488.7268409408722` do not work with `youtube` (maybe they used to but now they don't)
timestamps using url params though still work. `?t=488.7268409408722` / `?a=b&t=488.7268409408722`

Would it be possible to update the extension to use url param timestamps _for youtube_?

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release, which addressed this issue and provided a fix. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
