### ISSUE TITLE
Fullscreen shortcut not working sometimes in external embeds

### ISSUE THREAD

**Issue by denemier** [aidenlx/media-extended#28]
after last update for double click to full screen (still no button)

**internal media files like ![[example.mp4]]**
- no full screen button, or i cant double click for full screen like external medias ![]()
- so only externals have full screen double click option

**Comment by AidenLx** [comment]
Fix in [4815ea](https://github.com/alx-plugins/media-extended/commit/4815ea840e10148e3db4d1e34cfceab9f80f8b89), will be release with new update

**Comment by denemier** [comment]
it's fixed now with the new update do you know why f shortcut doesnt work in this case?
for external links like ![](embedcode):
- when I click the big centered play button to start video then press f it doesn't work
- but when i click bottom timeline play/stop button and click f shortcut it can switch to full screen

I don't have this issue with internal media at all,  internal media with f shortcut works for centered button and timeline play/stop button very well

**Comment by denemier** [comment]
this isn't very important, but just small one feature correction.

**Comment by AidenLx** [comment]
It seems to be an upstream bug related to Plyr. I'll keep the issue here but probably won't fix it.
