### ISSUE TITLE
Feature: Capture Screenshot of Video

### ISSUE THREAD

**Issue by okerivy** [aidenlx/media-extended#31]
Hope to add the screenshot function, screenshot, with a time stamp.
like this

    [[media.mp4#t=2]]
    ![[screenshot.png]]

**Comment by okerivy** [comment]
I think if the image is on top, and show the time,
in preview mode, it might be more comfortable to read, 
Because I might want to take notes
like this

```
![[screenshot.png]]
[01:11](media.mp4#t=71)
....my note
....my note balabala
```

**Comment by AidenLx** [comment]
Related topic: https://github.com/sampotts/plyr/issues/580

**Comment by dummifiedme** [comment]
+1

**Comment by EternalHXP** [comment]
Plz , Wait if for long long time . Thanks!
I have a dream 
 that one day  I can open a video at ipad obsidian in my home way. 
  then I can use the media capture button to create video image and timestamp,
  then I can handle the file adding info  by mac  with the image(ipad capture) when I get home
🤩🤩🤩

**Comment by jzhang-brex** [comment]
Hi there, is this already supported? I can't seem to find the screenshot button. :(
