### ISSUE TITLE
Default hotkey conflict

### ISSUE THREAD

**Issue by ngirard** [aidenlx/media-extended#33]
Using Media extended 2.6.0 along with Obsidian 0.12.3 on Ubuntu 21.04.

With the extension enabled, typing Ctrl-t to insert a template (which is the default template for this command) doesn't work any more.
Disabling the extension restores the expected behaviour.

Cheers, and thanks for your work !

**Comment by AidenLx** [comment]
You can fix this by going to shortcut settings to resolve conflict. It should be marked red.

**Comment by ngirard** [comment]
Sure. I was trying to hint towards a solution that wouldn't conflict with such an important core command.

Dealing with templates is a fundamental activity in Obsidian, so its shortcut should in my opinion have priority over "Getting a timestamp from player".
The default `Ctrl-t`shortcut is definitely hardwired to inserting a template in my brain. I think it can be safely assumed that many other Obsidian users are in the same situation.

Thus the issue shouldn't be regarded as closed yet, in my opinion.

Cheers

**Comment by AidenLx** [comment]
Any suggestions on the default hotkey? It seems that `ctrl-shift-t` is occupied by Advanced Table.

**Comment by ngirard** [comment]
@AidenLx, thanks for your understanding !

That's indeed a tricky question.
Here's what I came up with so far.
The other extensions I've installed use the following combinations of dead keys:
```
Ctrl
Ctrl + Shift
Alt
Alt + Shift
Ctrl + Alt + Shift
```

**As for which active letter to use**

The consonants of the word "timestamp" seem like good candidates: t, s, m, p.

The colon ':' character would be nice to use, as it reminds of timestamps since it's the only normalized character used as separator for time components (e.g. iso 8601).

Unfortunately, Obsidian (as VS Code btw) suffers from the severe limitations from Electron regarding keyboard events handling. As a consequence, the ':' character is *not* guaranteed to be reached by typing the ':' key on non-Qwerty keyboards. For instance, in order to comment out some text using my French keyboard layout, I need to type `Ctrl + :` to generate a keyboard event that Obsidian interprets as `Ctrl + /`.
Therefore, using any shortcut involving `:` would but make the current state of affairs more confusing IMHO -- to non-english users, meaning.

I cannot devote more time to the matter this morning, but will gladly come back to it later if you need to.

Hope that helps !

**Comment by AidenLx** [comment]
Thanks a lot! I get your point, and the problem you've mentioned is because `:` is mostly an alternative symbol that is assigned to different keys across layouts. Maybe I should set it to `ctrl + ;` to avoid this situation, as it can be type directly in most layout. What's your opinion on this?

**Comment by ngirard** [comment]
Sorry for the late reply.

Unfortunately the problem is similar with `:`.
Hitting `Ctrl + :` on my keyboard is interpreted as `Ctrl + .` by Obsidian -- by the way, my keyboard is a regular, vanilla, no-fancy French keyboard with an Azerty layout, as used by 10s of millions of people.
The `:` key on a Qwerty keyboard is located at the same location as `m` on Azerty keyboards ; but hitting `Ctrl + m` as not interpreted as a `Ctrl + :` event by Obsidian but as a `Ctrl + m` event.
By trial and error, I found that I have to type `Ctrl + $` on my keyboard to generate such `Ctrl + :` event, whereas the `$` key corresponds to the`]` key on a Qwerty layout... go figure.

**Comment by AidenLx** [comment]
I started to feel that this problem should be addressed in an bug report in the forum, instead of here. For now, I'll probably choose a letter key in favor of a symbol key for now.

**Comment by ngirard** [comment]
Absolutely, yes.

I'm not visiting the forum that often, but there must be a thread dedicated to the problem, as long as some issues within the Electron repo. I'll link to them from here when I have a chance to find them.

**Comment by ngirard** [comment]
> This topic may be relevant: https://forum.obsidian.md/t/international-keyboard-layout-hotkeys-not-working/524?u=aidenlx

It definitely is, good catch !

**Comment by ngirard** [comment]
A relevant comment from that thread which contradicts my (admittedly fuzzy) recall of the issue:

> VS Code is also based on Electron and there’s no such problem there: hotkeys in all major keyboard layouts work perfectly fine.

**Comment by AidenLx** [comment]
You should post your findings on the forum, so that @licat may come up with a fix.
