### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by gmmazza** [aidenlx/media-extended#35]
Have a video with a 4:3 aspect ratio and shows cropped in the view. It happens with YouTube link, in local file shows the black bars vertically at the sides.

**Comment by AidenLx** [comment]
Can you give me the raw text you were using? What theme are you using?

**Comment by gmmazza** [comment]
Hello AindenLx, I made a mistake the videos are 16:9 1920x1080. Created new pages and when paste the same link, it works as it should. Have the plugin sliding panes and updated today and believed for a moment that was the cause. Also tried changing the themes, and all I have installed works the same, including the obsidian standard. In every new page works now, but when I come back to the same page in obsidian, do the same. Paste the same link. So, I can't reproduce now, I will work to find the strange behaviour. Please put this on hold. Thank you!

**Comment by AidenLx** [comment]
Ok, I'll close this issue for now. Feel free to reopen it when it occurs again 😉

**Comment by AidenLx** [comment]
By the way aspect ratio for all YouTube video is fixed to 16:9 due to api restrictions.

**Comment by gmmazza** [comment]
It's odd. Thank you!

**Comment by gmmazza** [comment]
Hello, I played again with this; I said that I have the Sliding pane plugin installed, this plugin forces the width of the page fixed. 
In the next videos split the page and changing the width I could see that the problem.
Here you can see the behaviour with local file and YouTube link.
Maybe this is a problem of the player not your plugin.
Wish you could make the height of the video to change to follow the aspect of the video. See that with the test vault without your plugins this works 

### Local file

https://user-images.githubusercontent.com/29898425/120071374-5ed24300-c065-11eb-8e28-ddc9e00b5cf2.mp4


### Youtube link


https://user-images.githubusercontent.com/29898425/120071379-6c87c880-c065-11eb-88d4-a14aaf01817e.mp4

### Standard obsidian

https://user-images.githubusercontent.com/29898425/120071860-6f83b880-c067-11eb-8e97-d2fd66fe4e7b.mp4
