### ISSUE TITLE
Feature: Hotkeys for playback control

### ISSUE THREAD

**Issue by gmmazza** [aidenlx/media-extended#36]
Maybe is a dumb request. 
Can you add the possibility to control the video with steps forward and backward, pause and play and change player speed to keyboard shortcuts? Could be great to control as taking notes.

**Comment by AidenLx** [comment]
Though plyr has [built-in shortcut support](https://github.com/sampotts/plyr#shortcuts), it seems to be broken for quite some time. So I'll keep this issue open until I've test it thoroughly.

**Comment by gmmazza** [comment]
Update, I was using a YouTube link inside a playlist. With local and direct YouTube links works. Sorry for the confusion.
