### ISSUE TITLE
Feature: Open Media View from File Explorer

### ISSUE THREAD

**Issue by brimwats** [aidenlx/media-extended#53]
As this plugin shows lots of different filetypes, it would be very useful to have a preview panel near the file manager that showed a preview of the file before opening.

**Comment by aidenlx** [comment]
Do you mean something similar to preview panel of Windows file explorer? ![](https://www.dummies.com/wp-content/uploads/494473.image0.jpg)

Or hover preview on file?

**Comment by brimwats** [comment]
That is 100% exactly what I mean :)
