### ISSUE TITLE
mkv format support?

### ISSUE THREAD

**Issue by jsjuris89** [aidenlx/media-extended#54]
@aidenlx All examples use `.mp4` its not very clear if this functionality should work on `.mkv` video files?

[This](https://i.imgur.com/gNe1WpH.png) is what I get trying to embed local .mkv.
I can only open it on default media player.

If `.mkv` is not supported is there any hope for it to work in future, maybe?

**Comment by aidenlx** [comment]
This feature is unlikely to be supported for the following reasons: 

1. `.mkv` files is [not supported by obsidian](https://help.obsidian.md/Advanced+topics/Accepted+file+formats)
2. `mkv` is a container format that can include various types of video/audio encoding, so as it may work sometimes, it won't work consistently across different clients (mobile/desktop) as some encoding may not be supported by the browser environment, which obsidian runs within. For example, `hevc` is supported in safari while chrome isn't, and `webm` is supported in chrome while safari isn't. 

So I'm going to close this issue as I won't be able to do too much about it.
