### ISSUE TITLE
black side border on video filling the width of note

### ISSUE THREAD

**Issue by hcgilje** [aidenlx/media-extended#55]
When I add a video without adjusting its size, the player fills the width of the note, but most of it is black borders.
I am using the maximum height of 30vh and a minimum width of 300 in the settings.
I would have expected the player to scale to have maximum size within the height constraint and no black borders on the side.
`![[media/c0030.mp4]]`
so something similar to what I achieve when applying a width constraint
`![[media/c0030.mp4|300]]`

**Comment by aidenlx** [comment]
can you post the screenshot of console output and the file that isn't scaled correctly?

**Comment by hcgilje** [comment]
https://imgshare.io/image/pcc21y
https://imgshare.io/image/pccrdw

not sure what you mean with the console.
One screenshot is with higher vertical size which makes the scaled down video look strange with black bars on top and bottom

**Comment by aidenlx** [comment]
Here is the way to check console: 

> To check for errors, first open the developer tools by pressing `Ctrl-Shift-I` on Windows/Linux or `Cmd-Opt-I` on macOS, and then go to the "Console" tab. If you want to save the error to a log file, you can right click on the error and choose "Save as...".

And could you also upload the mp4 file directly to GitHub? It can be helpful to debugging.

**Comment by hcgilje** [comment]
https://user-images.githubusercontent.com/1252621/127469409-bb344392-f00f-42ac-9fd6-ff7c5ebc04e5.mp4

[obsidian.md-1627551041293.log](https://github.com/aidenlx/media-extended/files/6899545/obsidian.md-1627551041293.log)
[obsidian.md-1627551059961.log](https://github.com/aidenlx/media-extended/files/6899546/obsidian.md-1627551059961.log)

**Comment by aidenlx** [comment]
I've released v2.10.0 that tried to solve this issue, and you can reopen it if it still happens.

**Comment by hcgilje** [comment]
It fixed the black border, but now this happens when going fullscreen (no errors or warnings in console):
![Screenshot from 2021-07-30 10-11-12](https://user-images.githubusercontent.com/1252621/127623074-acaa070d-1dfa-419e-b64b-97f89e0cfa35.png)

**Comment by hcgilje** [comment]
I turned off a css snippet related to images and then the video is centered, but still not fullscreen (which worked before the update)
![Screenshot from 2021-07-30 10-17-48](https://user-images.githubusercontent.com/1252621/127623673-98d66c39-eefc-433b-9697-735c36bf24a6.png)

**Comment by aidenlx** [comment]
should be fixed in v2.10.2
