### ISSUE TITLE
Feature:  Timestamp offset in recording

### ISSUE THREAD

**Issue by ceciltech** [aidenlx/media-extended#59]
When using Get Current Timestamp of Recording it uses the exact timestamp, there is always a delay from when something was said to when I am able to use shortcut to insert timestamp.  It would be very nice to have a setting for a default number of seconds to be subtracted from the timestamp from when the command happened.  Beyond a default maybe following the command directly with a number could subtract that number  of seconds from the timestamp on replacement since often it takes more time to realize you want a note at a particular timestamp.

**Comment by xidlegend** [comment]
The timestamp option is not showing for me in the command palette, but it is in the hotkey section... and the hotkey doesnt do anything either

I am following instructions from this page https://github.com/aidenlx/media-extended/wiki/get-timestamp

**Comment by aidenlx** [comment]
> The timestamp option is not showing for me in the command palette, but it is in the hotkey section... and the hotkey doesnt do anything either
> 
> I am following instructions from this page https://github.com/aidenlx/media-extended/wiki/get-timestamp

You can check the updated instructions that should solve your problem.

**Comment by xidlegend** [comment]
Great!!

**Comment by xidlegend** [comment]
It took me a while to figure this out... but its important to right click the link,, and a separate media view pane opens... instead of opening a note preview pone like i was doing so far!!!
