### ISSUE TITLE
Overwrites current file data with data that was there when the player was first opened

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [aidenlx/media-extended#64]
- I click the star to add a timestamp, and it adds it to the start of the file rather than the cursor location,
- I take some notes after moving the timestamp to where it should be,
- I click the star again,
- Not only does it still prepend the timestamp to the file contents, it uses old file contents (I'm guessing because it's reading from the cache) and erases any notes I've taken. 

The first timestamp is still where it was before moving, so something must happen after inserting a timestamp that causes the cash to refresh, but it doesn't refresh afterwards.

**Comment by aidenlx** [comment]
Which version of obsidian and Media Extended are you using? and could you also post your screen recording for me to replicate the issue? (Github support mp4 uploads in issue)

**Comment by geoffreysflaminglasersword** [comment]
I'm not sure what changed but I can't reproduce it any longer, this was on version 2.10.3
