### ISSUE TITLE
Grouped notes forced to keep in sync to active note

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [aidenlx/media-extended#65]
If I have links to the same video in multiple different notes, clicking the first link opens the player, but clicking a link in another note opens a new player.
I'd like the option to always use the same player.

Ideally it'd be a dropdown with 3 options:
- always use a new player
- use the same player for the same media
- use the same player for all media

**Comment by aidenlx** [comment]
I've forgot to mention this on wiki, sorry about that😳. Here is the explanation: https://github.com/aidenlx/media-extended/wiki/Open-Links-in-One-Shared-Player

**Comment by geoffreysflaminglasersword** [comment]
> I've forgot to mention this on wiki, sorry about that😳. Here is the explanation: https://github.com/aidenlx/media-extended/wiki/Open-Links-in-One-Shared-Player

![ScreenLinkBug](https://user-images.githubusercontent.com/31261158/128605471-22ebe387-873f-437d-81fd-3537b9ae20b6.gif)

If I link two panes to the same player though, it ends up making both panes contain the same note

**Comment by aidenlx** [comment]
OK, got it. It happens when you switch between preview and edit mode, right? It seems that obsidian is forcing all linked panes in sync, hence the problem. More monkey-patches that need to be done. 🧐

**Comment by geoffreysflaminglasersword** [comment]
> OK, got it. It happens when you switch between preview and edit mode, right? It seems that obsidian is forcing all linked panes in sync, hence the problem. More monkey-patches that need to be done. 🧐

For me it actually happens whether you start in edit or preview mode

**Comment by aidenlx** [comment]
I should probably mention this to developer Licat. It seems so weird to have more than two panes share the same note and scroll location. The group feature can be improved.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release which provide a new implementation of linked pane through media note field. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
