### ISSUE TITLE
Feature: Add Commands for Pip toggle

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [aidenlx/media-extended#66]
I'd like to be able to dock a player in the sidebar, but unfortunately that makes the view buttons disappear.

Though that issue may be unique to me, I'd guess even with the player in a normal view most people would want hotkeys for PIP mode and adding timestamps from the currently active player

**Comment by aidenlx** [comment]
Related: #8

**Comment by geoffreysflaminglasersword** [comment]
> A command is already available for adding timestamps: https://github.com/aidenlx/media-extended/wiki/Get-Timestamp
> 
> Related: #8

If anyone else is wondering why that command isn't showing up, it apparently only shows up when the pane is linked to the video player

**Comment by geoffreysflaminglasersword** [comment]
> A command is already available for adding timestamps: https://github.com/aidenlx/media-extended/wiki/Get-Timestamp
> 
> Related: #8

Actually, this doesn't really solve the main problem, which is that docking the player in the sidebar doesn't work. If I link the player with a note, then move the player to the sidebar, it's no longer linked and the timestamp hotkey doesn't work

If I get the chance I can try to fix that, but I'm guessing it might require substantial changes behind the scenes since Obsidian just doesn't allow linking sidebar panes. 

Maybe media-extended could store a reference to the most recently focused player and default to using that for timestamps when a pane isn't linked.
