### ISSUE TITLE
Timestamps create a lot of graph clutter

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [aidenlx/media-extended#68]
The graph sees timestamps as tags because of the hash, is it a simple fix to have an alternate symbol or format?

Edit: Looks like they aren't actually treated as tags, but notes or something else... the only way to filter them is to filter by "-line:#t" but that also filters out the note and any of the notes other links

**Comment by aidenlx** [comment]
Could you send me a zip of test vault to illustrate this issue?
