### ISSUE TITLE
Please don't blur media on pause

### ISSUE THREAD

**Issue by andreiRS** [aidenlx/media-extended#69]
While watching a YouTube video I usually pause to take a timestamp and write notes. When paused, the player is blurred and any diagrams or text on the screen is completely obfuscated.  

A workaround is to use the YouTube builtin controls. However that options with distracting extras from YouTube like "more videos" or recommendation bar.

I would appreciate if the image would remain clear while the video is paused.

**Comment by aidenlx** [comment]
Please check setting tab for option. And for distracting "more video", you have to close them manually as YouTube does not allow to hide it by default.

**Comment by andreiRS** [comment]
I am running version 2.10.3 and I don't find in the setting tab any option related with not having the video blurred when it is paused. Did I missed it? What is the name of the setting?

**Comment by andreiRS** [comment]
Found it. The blur is on only when "Hide Recommend Videos" is on. Thanks for the quick reply!

**Comment by aidenlx** [comment]
It won't be shown if you enabled YouTube built-in controls. If you turn that off, you should see Hide Recommend Videos option.

**Comment by jayliu50** [comment]
The setting could probably be called "Blur Video on Pause" and not "Hide Recommended Videos" which would communicate clearer to the user what will happen.

Thank you so much for this wonderful plugin!
