### ISSUE TITLE
[feature request] To support getting a page reference stamp of an opened pdf files in obsidian

### ISSUE THREAD

**Issue by Ravenclawer** [aidenlx/media-extended#73]
I really like the feature of clicking the pentagram to get a timestamp from an opened video in the [[myvideo.mp4#t=XXXX]] format.
![image](https://user-images.githubusercontent.com/73892411/131144319-7148d4be-47d1-466f-a68a-d5a24fbb4a16.png) 
The pdf page reference in obsidian is quite similar to the timestamp by Media extended plugin, which is in the [[mypaper.pdf#page=YY]] format.
So, I wonder if the media extended plugin could "extend " its functionality a little bit to include creating pdf reference format in the pentagram.

**Comment by aidenlx** [comment]
This is way out of the scope of this plugin 😂 You may need to find other plugins that use a custom pdf reader like pdf.js instead of the built-in one as it is not exposed to API in any way.
