### ISSUE TITLE
More templates especially for Cursor control

### ISSUE THREAD

**Issue by dummifiedme** [aidenlx/media-extended#81]
When I am taking notes, its essential that we can have cursor control to move the cursor to a location after inserting time link.

for example:

I mostly want my notes to be of the form
`- Some text {{timestamp}}.`

While doing this, if I insert timestamp, I need to then go back to the staarting point and then type the thing. If it was possible to have a template for cursor then we could have a template like : `{{cursor}}{{TIMESTAMP}}`

It would help other users too depeding on how they take and format note :)

Templater plugin has this function called `tp.file.cursor()` for the same thing, maybe something like take could be explored.

**Comment by aidenlx** [comment]
Moved to #32
