### ISSUE TITLE
Add icons for Mobile Quick Action toolbar.

### ISSUE THREAD

**Issue by ryankhart** [aidenlx/media-extended#82]
I'm not sure yet how feasible this is, but on mobile (Android at least), the two icons that are used for the two commands below look like question marks:

Media Extended: Get Current Timestamp of Recording
Media Extended: Get timestamp from player

On mobile, there doesn't seem to be an option to show a text label or tooltip.

This is as much of an Obsidian problem as it is a plugin problem, but I think that the simplest solution, for now, would be to add icons to those commands. But I've never tried developing my own plugin yet, so I don't know how difficult that is.

**Comment by ryankhart** [comment]
![Screenshot_20210914-201659.jpg](https://user-images.githubusercontent.com/3673962/133365722-8699814f-474b-456b-9959-a35248ce841d.jpg)

**Comment by aidenlx** [comment]
It's not officially supported by obsidian, but meanwhile, you can use [advanced-toolbar](https://github.com/phibr0/obsidian-advanced-toolbar) to get icons working.
