### ISSUE TITLE
Feature: Support native timestamp from YouTube/bilibili

### ISSUE THREAD

**Issue by Danifood** [aidenlx/media-extended#83]
This one for example : https://youtu.be/wB89lJs5A3s?t=702
I need to add "#" before "t" to make it work with Media-Extend
Is there any settings to change this?

**Comment by aidenlx** [comment]
Hopefully YouTube will add other jump formats `?t=` because there are other styles for the default copy back format.
Such as this `?t=299 ` 
This is currently the only support`#t=299 `

 https://youtu.be/FuKEpOhiVPg?t=299  can't jump
 https://youtu.be/FuKEpOhiVPg#t=299  can jump

_Originally posted by @okerivy in https://github.com/aidenlx/media-extended/issues/15#issuecomment-844649561_

**Comment by Danifood** [comment]
Yeah, it will make lots of things easier.
Lots of other app like memex or Yinote can carry timestamp.

The biggest problem for me using Media-Extend for Youtube annotations and getting timestamp is that i can't use chrome plugin :""video speed controller" in obsidian，which is essential for me...

**Comment by aidenlx** [comment]
Speed control is [available in Media Extended](https://github.com/aidenlx/media-extended/wiki/Speed-Control) already, so what feature is missing exactly?

**Comment by Danifood** [comment]
I think i'm just too used to controlling speed by keyboard shortcuts.

**Comment by Vuccappella** [comment]
@Danifood I use the same extension and opened a request to add keyboard shortcuts to speed controls: https://github.com/aidenlx/media-extended/issues/77 

This is also what's stopping me from using the extension non stop. Currently going back between Memex and Media Extend in Obsidian due to this.

**Comment by Archie-2021** [comment]
i really hope you find a solution for this issue. this plugin is awesome and i just need to fix this to use this plugin in my workflow without any fiction

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release which address this issue. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
