### ISSUE TITLE
Jump to a specific time in the same tab

### ISSUE THREAD

**Issue by raftelo** [aidenlx/media-extended#87]
Is there a way to jump to a timestamp without opening a media view? From the screenshot below, I linked to an embedded video then I created a `### Notes` section, I would like a click on `local timestamp 1` to control the video above it, the current implementation opens the video in a new tab.

![Screenshot_20211005_124137](https://user-images.githubusercontent.com/74635692/136016024-542f3b18-dba6-444c-9e75-0eaf0fdea429.png)

**Comment by z-jason** [comment]
+1 to this request

**Comment by HamedAghaei** [comment]
It's a great idea! 
In addition to that, it would be great if the screenshot of a specific frame or time in a video would be shown when I roll over the mouse to an embedded link.

**Comment by uwe999** [comment]
+1

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release which add support for media note. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
