### ISSUE TITLE
Video progress cannot be controlled with arrow keys and space when use Youtube built-in controls

### ISSUE THREAD

**Issue by Hanxiao-Adam-Qi** [aidenlx/media-extended#92]
Hi!
Thank you for this fantastic Plugin, and it's really helpful!
Just found a minor issue when I switched on the Youtube Built-in Controls (because I need the subtitles). I can't use arrow keys and space to control the Video progress and pause. Could you fix that? 

Thank you!

**Comment by Archie-2021** [comment]
I second that. it is very vital for work with YouTube material. space for pause and play, jumping forward and backward, and adding hot keys for increasing, decreasing and turning the play speed to normal, and higher and lower volume is needed. 

and thanks for this great plugin
