### ISSUE TITLE
Feature: `webview` support for general video hosts

### ISSUE THREAD

**Issue by wslldsdhii** [aidenlx/media-extended#96]
一些在线培训视频网站，需要登录才可以看视频，比如：博学谷（传智播客）.
一些视频网站需要vip才可以看到的内容，需要登录。
如果可以提供一个 设置表格，通过键值对，配置，什么网站，使用什么token进行登录，那就把可用范围拓宽太多了。
比如配置页可以有：
youku.com : <MY-TOKEN1>
itheima.com : <MY-TOKEN2>

**Comment by Mollyoyo** [comment]
是啊，真的很需要这个功能，这个插件真的很好，但是却支持两个网站，太可惜了

**Comment by aidenlx** [comment]
v3目前已经支持bilibili登录，未来会考虑支持任意网站嵌入
