### ISSUE TITLE
Feature: Open the video on navigator 

### ISSUE THREAD

**Issue by robertofgama** [aidenlx/media-extended#98]
Hello, will be great if we have a way to open a video on navigador, because sometimes i want to see the video in another plataform and i need copy the link and paste on navigator, instead just click or right click on him.

**Comment by Elaws** [comment]
I've found a **dirty** workaround :

Whenever you want to open a YouTube link in navigator, just use `https://youtube.com/watch?v=youtubeID` instead of `https://www.youtube.com/watch?v=wtHra9tFISY`, and delete `case "youtube.com":` in the `main.js` of media-extended plugin.

**Comment by aidenlx** [comment]
It'll be handled properly in v3, I've added context menu option for link to open in browser
